name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: adRn-s
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_trim: yes
          #plugin_isocalendar: yes
          #plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: [most-used, recently-used]
          plugin_languages_recent_days: 150
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: history
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          plugin_reactions: yes
          plugin_sponsorships_sections: yes

# https://metrics.lecoq.io
# https://github.com/lowlighter/metrics#-documentation
# https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md
