name: Metrics

on:
  schedule: [{cron: "0 0 * * 1"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: adRn-s
          filename: metrics.svg 
          template: terminal
          base: header, activity, community, repositories, metadata
          config_animated: yes
          config_timezone: UTC
          plugin_followup: yes
          plugin_languages: yes
          plugin_pagespeed: no
          plugin_pagespeed_detailed: no
          plugin_lines: yes
